### ISSUE TITLE
mail delevery bug smime out of webapp ?

### ISSUE THREAD

**Issue by osnet** [mlan/docker-kopano#21]
hola, 
i've been messing araound with  s/mime ... 
i generated a free cert  at  [DGN](https://www.dgn.de/dgncert/)

upload in webapp OK

then i tried to add my signature to a mail and got this:

```
   554 5.6.0 bounce, id=4022781-10 - bad header

This nondelivery report was generated by the program amavisd-new at host
vsrv-postfix.pwr-srv.net. Our internal reference code for your message is
4022781-10/O6kaLUNfWEkG

INVALID HEADER

  Duplicate header field: "MIME-Version"

```
for the record : my spooler uses the external postfix, not the mta container.
Sending a pgp mail with evolution works fine.

i guess the  smime plugin  is  broken ?

**Comment by mlan** [comment]
Hi @osnet 

Interesting. When I look at the mail header of a signed mail I find:
```
X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "MIME-Version"
```
This is the milter in mlan/postfix-amavis that is checking outgoing mail. It appears that amavis fixes the header before it sends it off, since there is only one "MIME-Version". 

If possible it would be very useful if you can share the relevant parts of the mail header that bounces. Perhaps you can capture it if you send the signed mail to a friendly place?

**Comment by mlan** [comment]
This issue has been reported [upstream](https://forum.kopano.io/topic/3707/s-mime-bad-header-section-duplicate-header-field-mime-version-in-kopano-11-0-1) but has not been addressed yet, unfortunately.

**Comment by mlan** [comment]
This is a bug in kopano-core. Unfortunately the kopano community software has been discontinued.
